services:
  mongo:
    image: mongo
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: qwerty
    volumes:
      - mongo_data:/data/db
      - mongo_config:/data/configdb
    networks:
      - backend

  mongo-express:
    image: mongo-express
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: admin
      ME_CONFIG_MONGODB_ADMINPASSWORD: qwerty
      ME_CONFIG_MONGODB_URL: mongodb://admin:qwerty@mongo:27017/
    networks:
      - backend

  userauth:
    image: kingcloudamazing/user_auth_service:1.0
    ports:
      - 5000:5000
    depends_on:
      - mongo
    env_file:
      - .env
    networks:
      - backend

volumes:
  mongo_data:
  mongo_config:

networks:
  backend:
